### ISSUE TITLE
Doesn't handle if user isn't sudoer

### ISSUE THREAD

**Issue by Akuukis** [iKlem/linux-screeps-server-manager#1]
Doesn't handle if user isn't sudoer, but just goes on with installer. As I made dedicated user for keeping server and it isn't sudoer, would be nice to know which dependencies I lack

**Comment by iKlem** [comment]
I haven't done some test when a user doesn't have the sudo rights because i do it all within my main user.
This is something i thought about and i'll add & test it for the next update.
