### ISSUE TITLE
Nice to automatically add steam_api to config

### ISSUE THREAD

**Issue by Akuukis** [iKlem/linux-screeps-server-manager#2]
It would be nice to ask for and automatically add steam_api to config. For example like this
```bash
sed -i -- "s/steam_api_key =/steam_api_key = ${steam_api}/g" screeps/server/.screepsrc
```

**Comment by iKlem** [comment]
This is something going with the auto login to steam to update the game.

**Comment by iKlem** [comment]
The new screeps server fix this issue :D  
Closed
