### ISSUE TITLE
Reproduced on Debian 8.6 x64 

### ISSUE THREAD

**Issue by Akuukis** [iKlem/linux-screeps-server-manager#4]
I can confirm that all claimed features works on Debian 8.6 x64 with steamworks_sdk_137. I suspect it is steamwork version sensitive as my script didn't work with newer steamworks.

**Comment by iKlem** [comment]
I've been using the PS with 1.38a and everything works. This is why i've made the check only on the "steamworks_*.zip" because the downloaded zip file is like "steamworks_sdk_NUMVER.zip".
