### ISSUE TITLE
Package.json error

### ISSUE THREAD

**Issue by ardentsword** [iKlem/linux-screeps-server-manager#5]
The package.json contains an incorrect line:
`  "dependencies": {
    "screeps": "^2.1.3",
  },`
this should be:
`  "dependencies": {
    "screeps": "^2.1.3"
  },`
(without the comma) otherwise it gives me an error.

**Comment by iKlem** [comment]
__(Edited)__
I've already seen this problem and the package.json file will be removed for the next update by a specific `.npm-init.js` file. This will avoid problem for me when pushing new versions.
